mailer_contract_test needs elistman-dev stack
Turns out the configuration set isn't optional after all. I got this
error when running `make test` while the elistman-dev stack was down:

--- FAIL: TestSendWithLiveSes (0.20s)
    --- FAIL: TestSendWithLiveSes/Success (0.20s)
        mailer_contract_test.go:77: assertion failed: error is not nil:
        send to success@simulator.amazonses.com failed: operation error
        SESv2: SendEmail, https response error StatusCode: 404,
        RequestID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx,
        NotFoundException: Configuration set <elistman-dev> does not
        exist.
FAIL
FAIL    github.com/mbland/elistman/email        1.177s
FAIL