Add {SENDER,UNSUBSCRIBE}_USER_NAME to sam-with-env
Forgot to include this in commit
68972479a2aa1f6ea45a7899128b3dc9d92757ef.

Caught by the dev CI/CD pipeline:
- https://github.com/mbland/elistman/actions/runs/4658310423/jobs/8243861793

  Error: Failed to create changeset for the stack: elistman-dev, An
  error occurred (ValidationError) when calling the CreateChangeSet
  operation: Parameters: [SenderUserName, UnsubscribeUserName] must have
  values