Remove dup cloudformation/types import
This duplicate import in cmd/aws_test.go broke the CI pipeline:

- https://github.com/mbland/elistman/actions/runs/5151016242/jobs/9275790868

  Error: cmd/aws_test.go:11:2: package
  "github.com/aws/aws-sdk-go-v2/service/cloudformation/types" is being
  imported more than once (ST1019)

  Error: cmd/aws_test.go:12:2: other import of
  "github.com/aws/aws-sdk-go-v2/service/cloudformation/types"
  exit status 1

Surprised go-staticcheck didn't catch it in VS Code. Redundant
safeguards FTW!