Revert running medium tests in CI
The last run failed due to the lack of an AWS region:

- https://github.com/mbland/elistman/actions/runs/5083785495/jobs/9135218604

--- FAIL: TestValidateAddressSucceedsUsingLiveDnsService (0.00s)
    address_contract_test.go:38: assertion failed: error is not nil:
    unexpected error while checking if mbland@acm.org suppressed:
    operation error SESv2: GetSuppressedDestination, failed to resolve
    service endpoint, an AWS region is required, but was not found

  --- FAIL: TestSendWithLiveSes (0.00s)
    --- FAIL: TestSendWithLiveSes/Success (0.00s)
        mailer_contract_test.go:64: assertion failed: error is not nil:
        send to success@simulator.amazonses.com failed: operation error
        SESv2: SendEmail, failed to resolve service endpoint, an AWS
        region is required, but was not found

--- FAIL: TestSesSuppressor (0.00s)
    suppressor_contract_test.go:25: assertion failed: error is not nil:
    unexpected error while checking if 0AtJ@elistman-test.com
    suppressed: operation error SESv2: GetSuppressedDestination, failed
    to resolve service endpoint, an AWS region is required, but was not
    found

I'm going to have to think through how I want to configure this, if I
want to enable this in CI at all.