Update Makefile target name that builds the Lambda
Should've been part of commit 756d4669a1d4fd851095ad2bdeef3748009e240e.

This could've been caught locally via 'make run-local', but was caught
by the CI/CD pipeline:
- https://github.com/mbland/elistman/actions/runs/4660170315/jobs/8247905879

  Build Failed
  Error: CustomMakeBuilder:MakeBuild - Make Failed: make: *** No rule
  to make target 'build-Function'.  Stop.